-- 고양이와 개는 몇 마리 있을까
SELECT
    ANIMAL_TYPE,
    COUNT(ANIMAL_TYPE)
        FROM ANIMAL_INS
        GROUP BY ANIMAL_TYPE;

-- 동명 동물 수 찾기
SELECT
    NAME,
    COUNT(NAME)
        FROM ANIMAL_INS
    GROUP BY NAME
    HAVING COUNT(NAME) > 1;

-- 입양 시각 구하기(1)
SELECT
    HOUR(DATETIME),
    COUNT(HOUR(DATETIME))
        FROM ANIMAL_OUTS
        WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19
        GROUP BY HOUR(DATETIME)
    ORDER BY HOUR(DATETIME);